name: Publish

on:
  push:
    branches: [main]
  repository_dispatch:
    types: publish-npm
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Fix permissions
        run: |
          sudo chown -R $USER:$USER ${{ github.workspace }}
          sudo chmod -R 755 ${{ github.workspace }}
        continue-on-error: true
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          clean: true
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Setup pnpm
        run: npm install -g pnpm
      - name: Get node_modules cache
        uses: actions/cache@v4
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Remove node_modules
        if: steps.node_modules.outputs.cache-hit != 'true'
        run: rm -rf node_modules
      - name: Install Dependencies
        uses: nick-fields/retry@v3
        if: steps.node_modules.outputs.cache-hit != 'true'
        with:
          timeout_minutes: 120
          retry_on: error
          max_attempts: 3
          command: pnpm install
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_TAG=v$(node -p "require('./package.json').version")
          gh release create $RELEASE_TAG --target=$GITHUB_SHA --title="$RELEASE_TAG" --generate-notes

      - name: Get package info
        id: package
        uses: andreigiura/action-nodejs-package-info@v1.0.2

      - name: Publish to npmjs next version
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.package.outputs.is-prerelease == 'true'}}
        run: echo ${{ steps.package.outputs.is-prerelease}} && npm publish --tag next

      - name: Publish to npmjs
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.package.outputs.is-prerelease == 'false' }}
        run: npm publish
